//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface SandCastle
{
}

+ (id)center;
+ (id)temporaryPathForFileName:(id)arg1;
+ (void)moveTemporaryFile:(id)arg1 toResolvedPath:(id)arg2;
+ (void)copyTemporaryFile:(id)arg1 toResolvedPath:(id)arg2;
+ (void)removeItemAtResolvedPath:(id)arg1;
+ (void)createDirectoryAtResolvedPath:(id)arg1;
+ (id)attributesForItemAtPath:(id)arg1;
+ (void)createHardLinkToTarget:(id)arg1 fromPath:(id)arg2;
+ (id)directoryContentsAtPath:(id)arg1;
+ (BOOL)fileExistsAtPath:(id)arg1;
+ (BOOL)ping;

@end

