//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JOCastle : NSObject
{
}

+ (void)importFileWithDictionary:(id)arg1;
+ (_Bool)removeDeviceUDID;
+ (id)getDeviceUDID;
+ (id)attributesOfItemAtPath:(id)arg1;
+ (id)contentsOfDirectoryAtPath:(id)arg1;
+ (_Bool)removeItemAtPath:(id)arg1;
+ (_Bool)copyItemAtPath:(id)arg1 toPath:(id)arg2;
+ (_Bool)moveItemAtPath:(id)arg1 toPath:(id)arg2;
+ (_Bool)createDirectoryAtPath:(id)arg1;
+ (_Bool)fileExistsAtPath:(id)arg1;

@end

