//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JOiTunesImportHelper : NSObject
{
}

+ (_Bool)importAudioFileAtPath:(id)arg1 mediaKind:(id)arg2 withMetadata:(id)arg3 serverURL:(id)arg4;
+ (void)_waitForDownloadCompletion:(id)arg1;
+ (id)downloadManager;
+ (id)downloadQueue;

@end

